export const projectsData = [

  {
    id: 9,
    slug: "brand",
    title: "Poster Ads",
    client: "FeedBird",
    category: "Brand",
    year: "2025",
    description: "This advertising poster design was originally created as part of a graphic design recruitment task from FeedBird, which involved producing two advertising posters for the CheongKwanJang Hong Sam Won product. The company operates in the high-quality herbal supplement industry, combining Korean red ginseng, red date extract, red berries, and other natural ingredients. The product is intended to help boost energy, enhance immune endurance, and support overall health.",
    tools: [
      {app: "Canva"},
    ],
    size: "small",
    links: [
      { label: "Instagram", url: "https://feedbird.com" },
      { label: "Facebook", url: "https://www.instagram.com/feedbirdcom/" },
      { label: "Linkedin", url: "https://web.facebook.com/feedbird.co/" },
      { label: "Website", url: "http://linkedin.com/company/feedbirdco/" }
    ],
    images: [
      { publicId: "version1_rq7slj" },
      { publicId: "version2_bdukm7" },
    ],
  },

  {
    id: 8,
    slug: "personal",
    title: "Poster",
    client: "Personal",
    category: "Poster Design",
    year: "2022 - Now",
    description: "These posters are shared on social media as a form of visual communication as well as a space for design exploration. Each design represents ideas, style experimentation, and different visual approaches. The creative process reflects the development of design skills over time. These works are then curated as part of a portfolio.",
    tools: [
      {app: "Adobe Illustrator"},
      {app: "Adobe Photoshop"},
    ],
    size: "medium",
    links: [
      { label: "Github", url: "https://www.linkedin.com/in/ilkhanul-khalik-262920391/" },
      { label: "Linkedin", url: "https://www.linkedin.com/in/ilkhanul-khalik-262920391/" },
      { label: "Instagram", url: "https://www.instagram.com/ilkhanul_" },
    ],
    images: [
      { publicId: "shiteeneger_wve4im" },
      { publicId: "ctlya_nonhgo" },
      { publicId: "over_s1n3ny" },
      { publicId: "heavy_ol9z26" },
      { publicId: "freepalestine_rwev3g" },
      { publicId: "ctlyalogo_kqeqf6" },
      { publicId: "joeposter_bu9jyu" },
    ],
  },

  {
    id: 7,
    slug: "alize",
    title: "Flyer Formalis",
    client: "Formalis",
    category: "Flyer Design",
    year: "2022 - Now",
    description: "A collection of flyer designs created from 2022 to the present, showcasing the evolution of visual style, creativity, and design approach across various projects, while adhering to client directions and requirements.",
    tools: [
      {app: "Adobe Illustrator"},
      {app: "Adobe Photoshop"},
      {app: "Canva"},
    ],
    size: "small",
    links: [
      { label: "Instagram", url: "https://www.instagram.com/formalis_lipia/" },
      { label: "Facebook", url: "https://www.facebook.com/formalis.lipia.71" },
      { label: "Youtube", url: "https://www.youtube.com/@formalislipiaofficial2425" },
    ],
    images: [
      { publicId: "daurah22_rtxbao" },
      { publicId: "rdf23_qf8efc" },
      { publicId: "ramadhan23_tfzysm" },
      { publicId: "flyrbc_jrsz9j" },
      { publicId: "flyrbc2_ljt5pw" }
    ],
  },

  {
    id: 6,
    slug: "kmb",
    title: "Flyer KMB",
    client: "KMB",
    category: "Flyer Design",
    year: "2022 - Now",
    description: "A collection of flyer designs created from 2022 to the present, showcasing the evolution of visual style, creativity, and design approach across various projects, while adhering to client directions and requirements.",
    tools: [
      {app: "Adobe Illustrator"},
      {app: "Adobe Photoshop"},
      {app: "Canva"},
    ],
    size: "small",
    links: [
      { label: "Instagram", url: "https://www.instagram.com/km_bulukumba/" },
      { label: "Facebook", url: "https://www.facebook.com/kmbulukumba/?_rdc=2&_rdr#" },
    ],
    images: [
      { publicId: "Socmed_ahgkqc" },
      { publicId: "bukber09_gt4ro0" },
      { publicId: "bukber16_ggcvyw" },
      { publicId: "1to1_rpy1ja" },
      { publicId: "twibbon_odpclm" },
      { publicId: "Ucapan_sdtt6l" },
    ],
  },

  {
    id: 5,
    slug: "baru-durian",
    title: "Baru Durian",
    client: "Baru Durian",
    category: "Logo Design",
    year: "2025",
    description: "The logo design embraces a nature-inspired concept, featuring a symbol that represents the durian fruit. This visual identity aims to create a friendly, modern, simple, and easily recognizable impression for customers.",
    tools: [
      {app: "Adobe Illustrator"},
    ],
    size: "small",
    links: [
      { label: "Tiktok", url: "https://www.tiktok.com/@barudurian0" },
    ],
    images: [
      { publicId: "Guidline-01_wlbovi" },
      { publicId: "Guidline-02_hyundv" },
      { publicId: "Guidline-03_krym0a" },
      { publicId: "Guidline-04_sj0k6z" },
      { publicId: "Guidline-05_sfbpaj" },
      { publicId: "Guidline-06_t4verx" },
      { publicId: "Guidline-07_vl5oik" },
      { publicId: "Guidline-08_f2w35u" },
      { publicId: "Guidline-09_qgvdva" },
      { publicId: "Guidline-10_dm1del" },
    ],
  },

  {
    id: 4,
    slug: "car-wash",
    title: "Car Wash",
    client: "Absoora",
    category: "Logo Design",
    year: "2025",
    description: "This logo is designed to represent a car wash service business that is clean, fast, and reliable. The simple yet strong visual form is combined with elements of water and vehicles, reflecting a commitment to service quality and customer satisfaction.",
    tools: [
      {app: "Adobe Illustrator"},
      {app: "Adobe Photoshop"},
    ],
    size: "medium",
    links: [
      { label: "Instagram", url: "https://www.instagram.com/absoora.coffee/" },
      { label: "Tiktok", url: "https://www.tiktok.com/@absoora.coffee" },
    ],
    images: [
      { publicId: "Guideline-01_a6yogk" },
      { publicId: "Guideline-02_sxfjpq" },
      { publicId: "Guideline-03_qnvkog" },
      { publicId: "Guideline-04_gjlevt" },
      { publicId: "Guideline-05_rfgjxl" },
      { publicId: "Guideline-06_vq2pal" },
      { publicId: "Guideline-07_etf1j2" },
      { publicId: "Guideline-08_nus46f" },
      { publicId: "Guideline-09_kyp3ys" },
      { publicId: "Guideline-10_jwy5iu" },
      { publicId: "Guideline-11_t6opuz" },
      { publicId: "Guideline-12_qrcxim" },
    ],
  },

  {
    id: 3,
    slug: "t-shirt",
    title: "Start With For",
    client: "Formalis",
    category: "T-Shirt Design",
    year: "2024",
    description: "This organizational t-shirt design adopts a black-and-white monochrome concept with a modern visual approach. Arabic typography and Islamic-inspired symbols are treated in a minimalist style to create an elegant, bold, and contemporary identity that reflects the organization's values.",
    tools: [
      {app: "Adobe Illustrator"},
      {app: "Adobe Photoshop"},
      {app: "Figma"},
    ],
    size: "small",
    links: [
      { label: "Instagram", url: "https://www.instagram.com/formalis_lipia/" },
      { label: "Facebook", url: "https://www.facebook.com/formalis.lipia.71" },
      { label: "Youtube", url: "https://www.youtube.com/@formalislipiaofficial2425" },
    ],
    images: [
      { publicId: "wback_qmvwtv" },
      { publicId: "bback_ahqfqf" },
      { publicId: "wfront_ssgcgg" },
      { publicId: "bfront_fzpddm" },
      { publicId: "wts_zrgl8n" },
      { publicId: "bts_ajju5h" }
    ],
  },

  {
    id: 2,
    slug: "kami",
    title: "KAMI",
    client: "KAMI",
    category: "Logo Design",
    year: "2024",
    description: "A complete brand identity design project including a logo, color palette, typography, and brand guidelines. Focused on a modern aesthetic that reflects the values of a local community brand.",
    tools: [
      {app: "Adobe Illustrator"},
    ],
    size: "small",
    links: [
      { label: "Instagram", url: "https://www.instagram.com/reels/DR0mUXpgYbK/" },
    ],
    images: [
      { publicId: "Guidline-01_kwmez3" },
      { publicId: "Guidline-02_x8vte9" },
      { publicId: "Guidline-03_wblghn" },
      { publicId: "Guidline-04_zl2ekc" },
      { publicId: "Guidline-05_n7p3m2" },
      { publicId: "Guidline-06_zekqzl" },
      { publicId: "Guidline-07_udcnfz" },
      { publicId: "Guidline-08_kl9m0h" },
      { publicId: "Guidline-09_hvqd35" },
      { publicId: "Guidline-10_k8qpxr" },
      { publicId: "Guidline-11_uil0uo" },
      { publicId: "Guidline-12_d6uylm" },
    ],
  },

  {
    id: 1,
    slug: "musyar",
    title: "Musyar XXII",
    client: "Formalis",
    category: "Logo Design",
    year: "2022",
    description: "The theme of regeneration is expressed through shapes, lines, and symbols that represent growth, continuity, and the transition of roles from one generation to the next. The logo serves not only as a visual identity for the event, but also as a symbol of renewal, unity, and the sustainability of the organization's values.",
    tools: [
      {app: "Adobe Illustrator"},
    ],
    size: "small",
    links: [
      { label: "Instagram", url: "https://www.instagram.com/formalis_lipia/" },
      { label: "Facebook", url: "https://www.facebook.com/formalis.lipia.71" },
      { label: "Youtube", url: "https://www.youtube.com/@formalislipiaofficial2425" },
    ],
    images: [
      { publicId: "msyr01_veoqys" },
      { publicId: "msyr02_bsrnil" },
      { publicId: "msyr03_banrxn" },
      { publicId: "msyr04_poltdg" },
      { publicId: "msyr05_dab3m4" },
      { publicId: "msyr06_mnmyku" },
      { publicId: "msyr07_nw6xah" },
      { publicId: "msyr08_w5tlqx" },
      { publicId: "msyr09_lsvuvp" },
      { publicId: "msyr10_cmftdy" },
    ],
  },
];
